"""Parser for CPLEX LP format files generated by JuMP.

Reads .lp files and converts them into scipy-compatible structures
for re-solving with perturbed parameters.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
from scipy import sparse
from scipy.optimize import linprog, OptimizeResult

logger = logging.getLogger(__name__)


@dataclass
class LPModel:
    """Parsed LP model ready for scipy.optimize.linprog."""

    variable_names: list[str] = field(default_factory=list)
    variable_index: dict[str, int] = field(default_factory=dict)
    c: np.ndarray = field(default_factory=lambda: np.array([]))
    A_ub: sparse.csr_matrix | None = None
    b_ub: np.ndarray = field(default_factory=lambda: np.array([]))
    A_eq: sparse.csr_matrix | None = None
    b_eq: np.ndarray = field(default_factory=lambda: np.array([]))
    bounds: list[tuple[float | None, float | None]] = field(default_factory=list)
    constraint_names_ub: list[str] = field(default_factory=list)
    constraint_names_eq: list[str] = field(default_factory=list)
    sense: str = "minimize"

    @property
    def n_vars(self) -> int:
        return len(self.variable_names)

    @property
    def n_constraints(self) -> int:
        n = 0
        if self.A_ub is not None:
            n += self.A_ub.shape[0]
        if self.A_eq is not None:
            n += self.A_eq.shape[0]
        return n

    def get_objective_groups(self) -> dict[str, list[int]]:
        """Group objective variables by type prefix for sensitivity analysis.

        Returns mapping of group_name -> list of variable indices in c.
        Groups derived from master_problem.jl variable naming:
        - tech_inv_y*_tN_*          -> "inv_tech_N"
        - trans_inv_y*_*            -> "inv_trans"
        - bat_tech_pow_inv_y*_btN_* -> "inv_bat_pow_N"
        - bat_tech_cap_inv_y*_btN_* -> "inv_bat_cap_N"
        - op_ll_*                   -> "op_load_shedding"
        - op_fre_loss_*             -> "op_fre_penalty"
        """
        groups: dict[str, list[int]] = {}
        tech_inv_re = re.compile(r"tech_inv_y\d+_t(\d+)_")
        trans_inv_re = re.compile(r"trans_inv_y\d+_")
        bat_tech_pow_re = re.compile(r"bat_tech_pow_inv_y\d+_bt(\d+)_")
        bat_tech_cap_re = re.compile(r"bat_tech_cap_inv_y\d+_bt(\d+)_")
        op_ll_re = re.compile(r"op_ll_")
        op_fre_re = re.compile(r"op_fre_loss_")

        for idx, name in enumerate(self.variable_names):
            if abs(self.c[idx]) < 1e-15:
                continue

            # bat_tech_* shares the "bat_" prefix; test before tech_inv.
            m = bat_tech_pow_re.match(name)
            if m:
                groups.setdefault(f"inv_bat_pow_{m.group(1)}", []).append(idx)
                continue

            m = bat_tech_cap_re.match(name)
            if m:
                groups.setdefault(f"inv_bat_cap_{m.group(1)}", []).append(idx)
                continue

            m = tech_inv_re.match(name)
            if m:
                groups.setdefault(f"inv_tech_{m.group(1)}", []).append(idx)
                continue

            if trans_inv_re.match(name):
                groups.setdefault("inv_trans", []).append(idx)
                continue

            if op_ll_re.match(name):
                groups.setdefault("op_load_shedding", []).append(idx)
                continue

            if op_fre_re.match(name):
                groups.setdefault("op_fre_penalty", []).append(idx)
                continue

        return groups

    def get_rhs_groups(self) -> dict[str, list[tuple[str, int]]]:
        """Group RHS constraint values by type for perturbation.

        Returns mapping of group_name -> list of (constraint_type, index).
        constraint_type is "ub" or "eq".

        Note: JuMP only emits names for constraints that were named in the
        Julia model. The master problem's nodal power-balance constraints are
        anonymous (exported as c1, c2, ...), so they cannot be grouped by name
        here; demand-RHS sensitivity is therefore only available when balance
        constraints carry a demand_bal_/power_balance_ label. The named RHS
        groups that DO exist in the master are re_ratio_* and max_curtailment_*.
        """
        groups: dict[str, list[tuple[str, int]]] = {}
        demand_re = re.compile(r"demand_bal_|power_balance_")
        re_target_re = re.compile(r"re_target_|re_ratio_")
        co2_re = re.compile(r"co2_|carbon_")
        budget_re = re.compile(r"budget_")
        curtail_re = re.compile(r"max_curtailment_|curtailment_lim")

        def classify(name: str) -> str | None:
            if demand_re.search(name):
                return "demand"
            if re_target_re.search(name):
                return "re_target"
            if curtail_re.search(name):
                return "curtailment_limit"
            if co2_re.search(name):
                return "co2_budget"
            if budget_re.search(name):
                return "cost_budget"
            return None

        for idx, name in enumerate(self.constraint_names_eq):
            key = classify(name)
            if key:
                groups.setdefault(key, []).append(("eq", idx))

        for idx, name in enumerate(self.constraint_names_ub):
            key = classify(name)
            if key:
                groups.setdefault(key, []).append(("ub", idx))

        return groups


def _parse_terms(expr: str, var_index: dict[str, int], n_vars: int) -> tuple[dict[int, float], float]:
    """Parse a linear expression like '1 x + 2.5 y - 3 z' into coefficient dict and constant.

    Returns (coefficients_dict, constant).
    """
    coeffs: dict[int, float] = {}
    constant = 0.0

    # Normalize: ensure spaces around + and -
    expr = expr.strip()
    if not expr:
        return coeffs, constant

    # Split into tokens: sign + coefficient + variable
    # Pattern: optional sign, optional coefficient, variable name
    token_re = re.compile(
        r'([+-]?)\s*'           # sign
        r'(\d+(?:\.\d+)?(?:e[+-]?\d+)?)?\s*'  # optional coefficient
        r'(\S+)?'               # optional variable name
    )

    # Better approach: split by + and - while keeping the sign
    # First, insert spaces around operators for splitting
    expr = re.sub(r'\s*\+\s*', ' + ', expr)
    expr = re.sub(r'\s*-\s*', ' - ', expr)
    parts = expr.split()

    i = 0
    sign = 1.0
    while i < len(parts):
        token = parts[i]
        if token == '+':
            sign = 1.0
            i += 1
            continue
        elif token == '-':
            sign = -1.0
            i += 1
            continue

        # Try to parse as number + variable or just variable or just number
        # Check if it's a pure number
        try:
            val = float(token)
            # Could be a coefficient followed by variable, or a constant
            if i + 1 < len(parts) and parts[i + 1] not in ('+', '-'):
                # Next token is a variable name
                var_name = parts[i + 1]
                if var_name in var_index:
                    coeffs[var_index[var_name]] = sign * val
                i += 2
            else:
                constant += sign * val
                i += 1
            sign = 1.0
            continue
        except ValueError:
            pass

        # It's a variable name (coefficient = 1)
        if token in var_index:
            coeffs[var_index[token]] = sign * 1.0
        i += 1
        sign = 1.0

    return coeffs, constant


def parse_lp_file(filepath: str | Path) -> LPModel:
    """Parse a CPLEX LP format file into an LPModel.

    The CPLEX LP format from JuMP has sections:
    - minimize/maximize (objective)
    - subject to (constraints)
    - Bounds
    - End
    """
    filepath = Path(filepath)
    logger.info(f"Parsing LP file: {filepath} ({filepath.stat().st_size / 1024:.0f} KB)")

    # Phase 1: Read all content and identify sections
    with open(filepath) as f:
        content = f.read()

    lines = content.split('\n')
    del content  # free memory

    # Find section boundaries
    section_starts: dict[str, int] = {}
    for i, line in enumerate(lines):
        stripped = line.strip().lower()
        if stripped in ('minimize', 'maximize'):
            section_starts['objective'] = i
            sense = stripped
        elif stripped == 'subject to':
            section_starts['constraints'] = i
        elif stripped == 'bounds':
            section_starts['bounds'] = i
        elif stripped == 'end':
            section_starts['end'] = i

    if 'objective' not in section_starts:
        raise ValueError("No minimize/maximize section found in LP file")

    # Phase 2: Collect all variable names from the entire file
    var_set: set[str] = set()
    # Scan objective and constraints for variable names
    var_name_re = re.compile(r'[a-zA-Z_][a-zA-Z0-9_,\[\]\.]*')

    obj_start = section_starts['objective'] + 1
    obj_end = section_starts.get('constraints', section_starts.get('bounds', len(lines)))

    # Parse objective line(s) - may span multiple lines
    obj_text = ""
    for i in range(obj_start, obj_end):
        line = lines[i].strip()
        if not line:
            continue
        # Remove constraint label (obj: ...)
        if ':' in line and i == obj_start:
            line = line.split(':', 1)[1]
        obj_text += " " + line

    # Extract variable names from objective
    # Pattern: coefficient followed by variable name
    for m in re.finditer(r'(?:^|[+\-\s])(\d+(?:\.\d+)?(?:e[+-]?\d+)?)\s+([a-zA-Z_]\S*)', obj_text):
        var_set.add(m.group(2))
    # Variables with implicit coefficient 1
    for m in re.finditer(r'(?:^|[+\-])\s*([a-zA-Z_][a-zA-Z0-9_,\[\]\.]*)', obj_text):
        candidate = m.group(1)
        if candidate.lower() not in ('obj', 'subject', 'to', 'bounds', 'end', 'minimize', 'maximize'):
            var_set.add(candidate)

    # Scan constraints for variables
    constr_start = section_starts.get('constraints', obj_end)
    constr_end = section_starts.get('bounds', section_starts.get('end', len(lines)))
    for i in range(constr_start + 1, constr_end):
        line = lines[i].strip()
        if not line:
            continue
        # Remove constraint name
        if ':' in line:
            line = line.split(':', 1)[1]
        # Remove comparison and RHS
        for op in ('<=', '>=', '='):
            if op in line:
                line = line.split(op)[0]
                break
        for m in var_name_re.finditer(line):
            candidate = m.group(0)
            # Skip pure numbers
            try:
                float(candidate)
                continue
            except ValueError:
                pass
            if candidate.lower() not in ('obj', 'subject', 'to', 'bounds', 'end'):
                var_set.add(candidate)

    # Scan bounds for additional variables
    bounds_start = section_starts.get('bounds', constr_end)
    bounds_end = section_starts.get('end', len(lines))
    for i in range(bounds_start + 1, bounds_end):
        line = lines[i].strip()
        if not line:
            continue
        for m in var_name_re.finditer(line):
            candidate = m.group(0)
            try:
                float(candidate)
                continue
            except ValueError:
                pass
            if candidate.lower() not in ('free', 'bounds', 'end'):
                var_set.add(candidate)

    # Create sorted variable list and index
    variable_names = sorted(var_set)
    var_index = {name: idx for idx, name in enumerate(variable_names)}
    n_vars = len(variable_names)
    logger.info(f"Found {n_vars} variables")

    # Phase 3: Parse objective
    c = np.zeros(n_vars)
    obj_coeffs, _ = _parse_terms(obj_text, var_index, n_vars)
    for idx, val in obj_coeffs.items():
        c[idx] = val

    # Phase 4: Parse constraints
    ub_rows: list[tuple[dict[int, float], float]] = []
    eq_rows: list[tuple[dict[int, float], float]] = []
    ub_names: list[str] = []
    eq_names: list[str] = []

    for i in range(constr_start + 1, constr_end):
        line = lines[i].strip()
        if not line:
            continue

        # Extract constraint name
        cname = ""
        if ':' in line:
            cname, line = line.split(':', 1)
            cname = cname.strip()

        # Determine constraint type and split LHS/RHS
        if '<=' in line:
            lhs, rhs = line.split('<=', 1)
            coeffs, const = _parse_terms(lhs, var_index, n_vars)
            rhs_val = float(rhs.strip()) - const
            ub_rows.append((coeffs, rhs_val))
            ub_names.append(cname)
        elif '>=' in line:
            lhs, rhs = line.split('>=', 1)
            coeffs, const = _parse_terms(lhs, var_index, n_vars)
            rhs_val = float(rhs.strip()) - const
            # Convert >= to <=: -lhs <= -rhs
            neg_coeffs = {k: -v for k, v in coeffs.items()}
            ub_rows.append((neg_coeffs, -rhs_val))
            ub_names.append(cname)
        elif '=' in line:
            lhs, rhs = line.split('=', 1)
            coeffs, const = _parse_terms(lhs, var_index, n_vars)
            rhs_val = float(rhs.strip()) - const
            eq_rows.append((coeffs, rhs_val))
            eq_names.append(cname)

    logger.info(f"Parsed {len(ub_rows)} inequality and {len(eq_rows)} equality constraints")

    # Build sparse matrices
    A_ub = None
    b_ub = np.array([])
    if ub_rows:
        ub_data, ub_row_idx, ub_col_idx = [], [], []
        b_ub = np.zeros(len(ub_rows))
        for r, (coeffs, rhs) in enumerate(ub_rows):
            b_ub[r] = rhs
            for col, val in coeffs.items():
                ub_data.append(val)
                ub_row_idx.append(r)
                ub_col_idx.append(col)
        A_ub = sparse.csr_matrix(
            (ub_data, (ub_row_idx, ub_col_idx)),
            shape=(len(ub_rows), n_vars),
        )

    A_eq = None
    b_eq = np.array([])
    if eq_rows:
        eq_data, eq_row_idx, eq_col_idx = [], [], []
        b_eq = np.zeros(len(eq_rows))
        for r, (coeffs, rhs) in enumerate(eq_rows):
            b_eq[r] = rhs
            for col, val in coeffs.items():
                eq_data.append(val)
                eq_row_idx.append(r)
                eq_col_idx.append(col)
        A_eq = sparse.csr_matrix(
            (eq_data, (eq_row_idx, eq_col_idx)),
            shape=(len(eq_rows), n_vars),
        )

    # Phase 5: Parse bounds
    bounds = [(0.0, None)] * n_vars  # default: x >= 0

    for i in range(bounds_start + 1, bounds_end):
        line = lines[i].strip()
        if not line:
            continue

        # Fixed variable: var = val
        fixed_m = re.match(r'^(\S+)\s*=\s*([+-]?\d+(?:\.\d+)?(?:e[+-]?\d+)?)\s*$', line)
        if fixed_m:
            vname, val = fixed_m.group(1), float(fixed_m.group(2))
            if vname in var_index:
                bounds[var_index[vname]] = (val, val)
            continue

        # Range: lb <= var <= ub
        range_m = re.match(
            r'^([+-]?\d+(?:\.\d+)?(?:e[+-]?\d+)?)\s*<=\s*(\S+)\s*<=\s*([+-]?\d+(?:\.\d+)?(?:e[+-]?\d+)?)\s*$',
            line,
        )
        if range_m:
            lb, vname, ub = float(range_m.group(1)), range_m.group(2), float(range_m.group(3))
            if vname in var_index:
                bounds[var_index[vname]] = (lb, ub)
            continue

        # var >= lb
        ge_m = re.match(r'^(\S+)\s*>=\s*([+-]?\d+(?:\.\d+)?(?:e[+-]?\d+)?)\s*$', line)
        if ge_m:
            vname, lb = ge_m.group(1), float(ge_m.group(2))
            if vname in var_index:
                bounds[var_index[vname]] = (lb, None)
            continue

        # var <= ub
        le_m = re.match(r'^(\S+)\s*<=\s*([+-]?\d+(?:\.\d+)?(?:e[+-]?\d+)?)\s*$', line)
        if le_m:
            vname, ub = le_m.group(1), float(le_m.group(2))
            if vname in var_index:
                bounds[var_index[vname]] = (0.0, ub)
            continue

        # var free
        free_m = re.match(r'^(\S+)\s+free\s*$', line, re.IGNORECASE)
        if free_m:
            vname = free_m.group(1)
            if vname in var_index:
                bounds[var_index[vname]] = (None, None)
            continue

    model = LPModel(
        variable_names=variable_names,
        variable_index=var_index,
        c=c,
        A_ub=A_ub,
        b_ub=b_ub,
        A_eq=A_eq,
        b_eq=b_eq,
        bounds=bounds,
        constraint_names_ub=ub_names,
        constraint_names_eq=eq_names,
        sense=sense,
    )
    logger.info(
        f"LP parsed: {model.n_vars} vars, {model.n_constraints} constraints, "
        f"{len(model.get_objective_groups())} obj groups"
    )
    return model


def solve_lp(model: LPModel) -> tuple[float, dict[str, float]]:
    """Solve the parsed LP model using scipy.optimize.linprog.

    Returns (objective_value, solution_dict).
    """
    sign = 1.0 if model.sense == "minimize" else -1.0
    result: OptimizeResult = linprog(
        c=sign * model.c,
        A_ub=model.A_ub,
        b_ub=model.b_ub,
        A_eq=model.A_eq,
        b_eq=model.b_eq,
        bounds=model.bounds,
        method="highs",
        options={"presolve": True, "time_limit": 300},
    )

    if not result.success:
        logger.warning(f"LP solve failed: {result.message}")
        return float("inf"), {}

    obj_val = sign * result.fun
    solution = {
        name: result.x[i]
        for i, name in enumerate(model.variable_names)
        if abs(result.x[i]) > 1e-10
    }
    return obj_val, solution


def extract_kpis(model: LPModel, obj_val: float,
                 solution: dict[str, float]) -> dict[str, float]:
    """Extract KPI values from an LP solution.

    Returns dict with keys:
    - total_cost
    - inv_gen_total (total generator investment MW)
    - inv_bat_total (total battery investment MW)
    - curtailment (total curtailment if available)
    - load_shedding (total load shedding)
    """
    kpis: dict[str, float] = {"total_cost": obj_val}

    # Sum investments by type
    gen_inv_total = 0.0
    bat_inv_total = 0.0
    curtailment = 0.0
    load_shedding = 0.0

    for name, val in solution.items():
        # bat_tech_* shares the "bat_" prefix; test before tech_inv.
        if name.startswith(("bat_tech_pow_inv_", "bat_tech_cap_inv_")):
            bat_inv_total += val
        elif name.startswith("tech_inv_"):
            gen_inv_total += val
        elif "curtail" in name.lower():
            curtailment += val
        elif name.startswith("op_ll_"):
            load_shedding += val

    kpis["inv_gen_total"] = gen_inv_total
    kpis["inv_bat_total"] = bat_inv_total
    kpis["curtailment"] = curtailment
    kpis["load_shedding"] = load_shedding

    return kpis


def perturb_and_solve(
    model: LPModel,
    obj_multipliers: dict[str, float] | None = None,
    rhs_multipliers: dict[str, float] | None = None,
) -> dict[str, float]:
    """Apply multipliers to objective coefficients and/or RHS, then re-solve.

    Args:
        model: Parsed LP model.
        obj_multipliers: Maps group_name -> multiplier for objective coefficients.
        rhs_multipliers: Maps group_name -> multiplier for RHS values.

    Returns:
        KPI dict from the perturbed solution.
    """
    # Copy arrays for perturbation
    c_pert = model.c.copy()
    b_ub_pert = model.b_ub.copy() if len(model.b_ub) > 0 else model.b_ub
    b_eq_pert = model.b_eq.copy() if len(model.b_eq) > 0 else model.b_eq

    # Apply objective multipliers
    if obj_multipliers:
        obj_groups = model.get_objective_groups()
        for group_name, mult in obj_multipliers.items():
            if group_name in obj_groups:
                for idx in obj_groups[group_name]:
                    c_pert[idx] *= mult

    # Apply RHS multipliers
    if rhs_multipliers:
        rhs_groups = model.get_rhs_groups()
        for group_name, mult in rhs_multipliers.items():
            if group_name in rhs_groups:
                for ctype, idx in rhs_groups[group_name]:
                    if ctype == "ub":
                        b_ub_pert[idx] *= mult
                    else:
                        b_eq_pert[idx] *= mult

    # Solve
    sign = 1.0 if model.sense == "minimize" else -1.0
    result = linprog(
        c=sign * c_pert,
        A_ub=model.A_ub,
        b_ub=b_ub_pert,
        A_eq=model.A_eq,
        b_eq=b_eq_pert,
        bounds=model.bounds,
        method="highs",
        options={"presolve": True, "time_limit": 300},
    )

    if not result.success:
        return {
            "total_cost": float("inf"),
            "inv_gen_total": float("nan"),
            "inv_bat_total": float("nan"),
            "curtailment": float("nan"),
            "load_shedding": float("nan"),
        }

    obj_val = sign * result.fun
    solution = {
        name: result.x[i]
        for i, name in enumerate(model.variable_names)
        if abs(result.x[i]) > 1e-10
    }
    return extract_kpis(model, obj_val, solution)
